config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/tasks' => 'tasks#index'

  get '/tasks/new' => 'tasks#new'
  post '/tasks' => 'tasks#create'

  get '/tasks/:id' => 'tasks#show', as: :task

  get '/tasks/:id/edit' => 'tasks#edit', as: :task_edit
  patch 'tasks/:id' => 'tasks#update'

  delete '/tasks/:id' => 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true
  validates :details, presence: true

  def completed?
    self.completed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save

    redirect_to task_path(@task)
  end

  def edit
  end

  def update
    @task.update(task_params)

    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

# ------------------------------------------------------------------------------
private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def find_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed unless @task.new_record? %>
  <%= f.check_box :completed unless @task.new_record? %>
  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<%= render "form", task: @task %>

app/views/tasks/index.html.erb
<div class="container">
  <h1>My tasks</h1>
  <% @tasks.each_with_index do |task, index| %>
  <%# INI TASK %>
    <div style="display:flex; align-items: center;">
      <p style="margin: 0; padding: 5px; width: 20px; text-align: center;"><%= index + 1 %></p>
      <% if task.completed? %>
        <input style="margin: 0; padding: 5px; width: 20px;" type="checkbox" checked>
      <% else %>
        <input style="margin: 0; padding: 5px; width: 20px;" type="checkbox">
      <% end %>
      <%= link_to task.title, task_path(task), class:"task-list"%>
    </div>
  <%# END TASK %>
  <% end %>
</div>
<%#   %>

app/views/tasks/new.html.erb
<%= render "form", task: @task %>

app/views/tasks/show.html.erb
<h2>
  <%= @task.title %>
</h2>
<p><%= @task.details %></p>

<div style="display: flex; align-items: center">
  <% if @task.completed? %>
    <input style="margin: 0; padding: 5px; width: 20px;" type="checkbox" checked>
  <% else %>
    <input style="margin: 0; padding: 5px; width: 20px;" type="checkbox">
  <% end %>
  <p>This task is completed</p>
</div>

<%= link_to "Delete this task",
            task_path(@task),
            method: :delete,
            data: { confirm: "Are you sure?" } %>
<p> </p>
<%= link_to "Edit this task", task_edit_path(@task) %>
<p> </p>
<%= link_to "List all tasks", tasks_path %>